<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>SpecPdfGenerator</AssemblyName>
    <RootNamespace>SpecPdfGenerator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp-GDI" Version="6.2.4" />
  </ItemGroup>
</Project>
